const ja = {
  "common": {
    "language": "Language",
    "back": "Back",
    "login": "Login",
    "logout": "Logout",
    "loading": "Loading order details...",
    "products": "Products",
    "store": "Store",
    "search": "Search products...",
    "searchAria": "Search products",
    "categories": "Categories",
    "allCategories": "All categories",
    "allProducts": "All products",
    "sort": "Sort products",
    "newest": "Newest",
    "cheapest": "Lowest price",
    "expensive": "Highest price",
    "byName": "By name",
    "product": "Product",
    "productsCount": "products",
    "collection": "Collection",
    "featured": "Featured products",
    "loadingProducts": "Loading products...",
    "errorTitle": "Error loading products",
    "error": "Failed to load products. Please try again.",
    "emptyTitle": "No products to display",
    "empty": "No products were found. Change your filters or search.",
    "categoryProducts": "Product categories",
    "image": "Product image",
    "available": "Available",
    "unavailable": "Unavailable",
    "wishlist": "Add to wishlist",
    "wishlisted": "Product in wishlist",
    "price": "ظ†آ¾طŒظˆآ آ¼",
    "currency": "Toman",
    "view": "View",
    "stock": "Stock",
    "quantity": "Quantity",
    "decrease": "Decrease quantity",
    "increase": "Increase quantity",
    "cart": "Cart",
    "viewCart": "View cart",
    "continueShopping": "Continue shopping",
    "addToCart": "Add to cart",
    "adding": "Adding...",
    "unavailableProduct": "Product unavailable",
    "noDescription": "No information has been provided for this product.",
    "category": "Category",
    "heroTitle": "Everything you need, right here.",
    "heroText": "Find selected products and choose with confidence.",
    "storeLabel": "Kolchi Store",
    "user": "User",
    "panel": "Admin panel",
    "orders": "My orders",
    "wishlistLink": "Wishlist",
    "loginRequired": "Please log in to add a product to your cart.",
    "addedToCart": "Product added to cart successfully.",
    "addToCartFailed": "Failed to add the product to the cart.",
    "errorGeneric": "Something went wrong. Please try again."
  },
  "auth": {
    "login": "Login",
    "loggingIn": "Signing in...",
    "alreadyLoggedIn": "You are already logged in",
    "backToStore": "Back to store",
    "username": "Username",
    "password": "Password",
    "noAccount": "アカウントをお持ちではありませんか？",
    "register": "Register",
    "addressTooShort": "The shipping address must be at least 10 characters.",
    "total": "Total amount",
    "emptyCartText": "You haven't added any products to your cart yet.",
    "placeOrder": "Place order",
    "placingOrder": "Placing order...",
    "shippingAddress": "Full delivery address",
    "emptyCart": "Your cart is empty",
    "phone": "Phone number",
    "orderFailed": "Failed to place the order.",
    "loginToOrder": "Please log in before placing an order.",
    "remove": "Remove",
    "loadingCart": "Loading cart...",
    "invalidPhone": "The phone number is not valid. Example: 09123456789",
    "phoneRequired": "Please enter your phone number.",
    "addressRequired": "Please enter the shipping address.",
    "address": "Shipping address",
    "shippingInfo": "Shipping information",
    "unitPrice": "Unit Price:",
    "clearCart": "Clear cart",
    "subtotal": "ظ‡آ°عˆأ¨آ¨ث†",
    "cartItemsCount": "{count} products in cart",
    "loginFailed": "Login failed.",
    "loadingOrder": "Loading order details...",
    "orderDetails": "Order details",
    "loginToViewOrder": "Please log in to view your order.",
    "orderNotFound": "Order not found.",
    "backToOrders": "Back to orders",
    "order": "Order",
    "orderPlaced": "Order placed",
    "unknownDate": "Unknown date",
    "orderTracking": "Order tracking",
    "trackingDescription": "The order status is shown based on the latest recorded stage.",
    "cancelledOrder": "Order cancelled",
    "cancelledOrderDescription": "This order has not entered the shipping process.",
    "currentStatus": "Current status",
    "notProvided": "Not provided",
    "orderProducts": "Order products",
    "itemsCount": "items",
    "noProductsInOrder": "No products were registered for this order.",
    "totalAmount": "Total amount",
    "payOrder": "Pay for order",
    "payingOrder": "Processing payment...",
    "cancelOrder": "Cancel order",
    "cancellingOrder": "Cancelling order...",
    "confirmCancelOrder": "この注文をキャンセルしてもよろしいですか？",
    "paymentLoginRequired": "Please log in before making a payment.",
    "paymentFailed": "Order payment failed.",
    "cancelFailed": "Order cancellation failed."
  },
  "adminMembers": {
    "accessDenied": "Access to member management is denied.",
    "loadError": "Failed to load store members.",
    "userIdRequired": "User ID is required.",
    "createDenied": "You are not allowed to add members.",
    "invalidMember": "Invalid member data.",
    "createError": "Failed to add member.",
    "roleChangeDenied": "You are not allowed to change member roles.",
    "roleChangeError": "Failed to change member role.",
    "deleteConfirm": "Delete product \"{name}\"?",
    "deleteDenied": "You are not allowed to delete members.",
    "deleteError": "Failed to delete member.",
    "loading": "Loading order details...",
    "title": "Member Management",
    "addMember": "Add Member",
    "userId": "User ID",
    "userIdPlaceholder": "Enter user ID",
    "role": "Role",
    "adding": "Adding...",
    "currentMembers": "Current Members",
    "memberCount": "Member count",
    "empty": "No members have been added to this store yet.",
    "userWithId": "User with ID",
    "userIdLabel": "ID",
    "delete": "Delete"
  },
  "adminOrders": {
    "status": {
      "pending": "Pending review",
      "confirmed": "Confirmed",
      "paid": "Paid",
      "shipped": "Shipped",
      "delivered": "Delivered",
      "cancelled": "Cancelled"
    },
    "accessDenied": "You are not allowed to view this store's orders.",
    "loadError": "Failed to load orders.",
    "statusChangeDenied": "Order status change is not allowed.",
    "statusChangeForbidden": "You are not allowed to change order status.",
    "statusChangeError": "Failed to change order status.",
    "loading": "Loading orders...",
    "title": "Order Management",
    "orders": "Orders",
    "orderCount": "orders",
    "empty": "No orders have been placed for this store.",
    "amount": "Amount",
    "user": "User",
    "phone": "Phone",
    "address": "Address",
    "items": "Order Items",
    "backToManagement": "Back to Management",
    "order": "Order"
  },
  "adminDashboard": {
    "unknownStore": "Store",
    "loading": "Loading admin panel...",
    "saving": "Saving...",
    "dashboard": "Store Management Dashboard",
    "backToStore": "Store",
    "appearanceDescription": "Configure theme, colors, radius, and component styles",
    "orders": "Orders",
    "accessDenied": "You do not have permission to manage this store.",
    "manageOrders": "Manage Orders",
    "storeManagementDescription": "Current store status and management information",
    "active": "Store Active",
    "manageMembers": "Manage Members",
    "saveError": "Failed to save store information.",
    "user": "User",
    "products": "Products",
    "manageProducts": "Manage Products",
    "inventory": "ظ‡إ“آ¨ظ‡ط›آ«",
    "store": "Store",
    "title": "Admin Panel",
    "saved": "Store information saved successfully.",
    "manageAppearance": "Manage Appearance",
    "settings": "Store Settings",
    "members": "Members & Roles",
    "inactive": "Store Inactive",
    "membersDescription": "Manage store members and their permissions",
    "description": "Description",
    "permissions": "権限",
    "accessPreview": "アクセスプレビュー",
    "storePreview": "ストアプレビュー",
    "storePreviewDescription": "現在のストア体験をプレビューします。",
    "apiMapTitle": "APIアクセスマップ",
    "apiMapDescription": "各ストア管理モジュールで利用可能な操作の概要です。",
    "apiMapStoreSettingsDescription": "ストアの設定と運用設定を表示・更新します。",
    "apiMapModule": "モジュール",
    "apiMapOperations": "操作",
    "apiMapDescriptionColumn": "説明",
    "roleEditor": "編集者",
    "roleViewer": "閲覧者",
    "removeMember": "メンバーを削除",
    "addTeamMember": "チームメンバーを追加",
    "addTeamMemberDescription": "ストアメンバーを作成し、初期ロールを設定します。",
    "addingMember": "メンバーを追加中...",
    "loadError": "Failed to load admin panel data.",
    "appearance": "Store Appearance",
    "productsDescription": "Create, edit, activate, and manage product inventory",
    "storeId": "Store ID",
    "inventoryDescription": "View and manage product inventory and warehouse transactions",
    "saveChanges": "Save Changes",
    "editDenied": "You do not have permission to edit this store.",
    "storeManagement": "Store Status",
    "manageInventory": "Manage Inventory",
    "ordersDescription": "View orders and manage order status",
    "storeName": "Store Name",
    "settingsDescription": "Manage the main store information.",
    "activeStore": "Store is active"
  },
  "adminProducts": {
    "nameRequired": "Please enter the product name.",
    "slugRequired": "Please enter the product's English identifier.",
    "priceRequired": "Please enter the product price.",
    "stockRequired": "Please enter the product stock.",
    "accessDenied": "You do not have permission to manage products for this store.",
    "loadError": "Failed to load product information.",
    "operationDenied": "You do not have permission to perform this operation.",
    "invalidProduct": "The product information is invalid.",
    "saveError": "Failed to save the product.",
    "toggleError": "Failed to change the product status.",
    "deleteConfirm": "Delete product \"{name}\"?",
    "deleteError": "Failed to delete the product.",
    "loading": "Loading products...",
    "managementPanel": "Management Panel",
    "title": "Product Management",
    "backToManagement": "Back to Management",
    "editProduct": "Edit Product",
    "newProduct": "New Product",
    "generalAndInventory": "General product information and inventory",
    "cancel": "Cancel",
    "productName": "Product name",
    "namePlaceholder": "e.g. Ethiopian Coffee",
    "slugPlaceholder": "e.g. ethiopian-coffee",
    "price": "Price",
    "pricePlaceholder": "e.g. 450000",
    "stock": "Stock",
    "stockPlaceholder": "e.g. 10",
    "category": "Category",
    "categoryPlaceholder": "e.g. Select coffee",
    "activeProduct": "Product is active",
    "description": "Description",
    "permissions": "権限",
    "accessPreview": "アクセスプレビュー",
    "storePreview": "ストアプレビュー",
    "storePreviewDescription": "現在のストア体験をプレビューします。",
    "apiMapTitle": "APIアクセスマップ",
    "apiMapDescription": "各ストア管理モジュールで利用可能な操作の概要です。",
    "apiMapStoreSettingsDescription": "ストアの設定と運用設定を表示・更新します。",
    "apiMapModule": "モジュール",
    "apiMapOperations": "操作",
    "apiMapDescriptionColumn": "説明",
    "roleEditor": "編集者",
    "roleViewer": "閲覧者",
    "removeMember": "メンバーを削除",
    "addTeamMember": "チームメンバーを追加",
    "addTeamMemberDescription": "ストアメンバーを作成し、初期ロールを設定します。",
    "addingMember": "メンバーを追加中...",
    "descriptionPlaceholder": "e.g. Ethiopian coffee with fruity aroma and balanced acidity",
    "saving": "Saving...",
    "saveChanges": "Save changes",
    "createProduct": "Create product",
    "products": "Products",
    "productCount": "products",
    "empty": "No products have been registered.",
    "active": "Active",
    "inactive": "Inactive",
    "priceLabel": "Price",
    "stockLabel": "Stock",
    "edit": "Edit",
    "deactivate": "Deactivate",
    "activate": "Activate",
    "delete": "Delete"
  },
  "wishlist": {
    "loading": "Loading wishlist...",
    "title": "Wishlist",
    "count": "{count} products in wishlist",
    "unauthMessage": "Please log in to view your wishlist.",
    "login": "Login",
    "fetchError": "Failed to load wishlist.",
    "removeError": "Failed to remove item from wishlist.",
    "emptyTitle": "You have not saved any products yet",
    "emptyMessage": "Save your favorite products here.",
    "backToStore": "Back to store",
    "productImage": "Product image",
    "product": "Product",
    "currency": "Toman",
    "remove": "Remove from wishlist"
  },
  "registerPage": {
    "title": "Owner Control Center",
    "username": "Username",
    "email": "Email",
    "phone": "Phone number",
    "password": "Password",
    "passwordConfirm": "Confirm password",
    "passwordMismatch": "Password and confirmation do not match.",
    "submitting": "Registering...",
    "submit": "Register",
    "alreadyRegistered": "すでにアカウントをお持ちですか？",
    "login": "Login",
    "error": "Registration failed."
  },
  "orders": {
    "status": {
      "pending": "Pending review",
      "confirmed": "Confirmed",
      "paid": "Paid",
      "shipped": "Shipped",
      "delivered": "Delivered",
      "cancelled": "Cancelled"
    },
    "loading": "Loading orders...",
    "title": "My Orders",
    "count": "{count} orders",
    "backToStore": "← Back to store",
    "unauthTitle": "My Orders",
    "unauthMessage": "Please log in to view your orders.",
    "login": "Login",
    "emptyTitle": "You have no orders yet",
    "emptyMessage": "Choose your favorite products and place your first order.",
    "order": "Order",
    "unknownDate": "Unknown date",
    "product": "Product",
    "quantity": "Quantity",
    "total": "Total amount",
    "currency": "Toman",
    "viewDetails": "View details",
    "cancel": "Cancel order",
    "cancelling": "Cancelling...",
    "cancelConfirm": "Are you sure you want to cancel order #{id}?",
    "authRequired": "You must be logged in to cancel an order.",
    "fetchError": "Failed to load orders.",
    "cancelError": "The order could not be cancelled.",
    "unknownStatus": "Unknown",
    "detailTitle": "Order details",
    "registeredOrder": "Order placed",
    "notFound": "Order not found.",
    "backToOrders": "Back to orders",
    "continueShopping": "Continue shopping",
    "detailFetchError": "Failed to load order details.",
    "trackingTitle": "Order tracking",
    "trackingDescription": "The order status is shown based on the latest recorded step.",
    "trackingRegistered": "Order placed",
    "trackingConfirmed": "Order confirmed",
    "trackingPayment": "Payment",
    "trackingShipping": "Shipping",
    "trackingDelivery": "Delivered",
    "currentStatus": "Current status:",
    "trackingCancelledTitle": "Order cancelled",
    "trackingCancelledMessage": "This order did not proceed to shipping.",
    "shippingTitle": "Shipping information",
    "phone": "Phone number",
    "address": "Shipping address",
    "notProvided": "Not provided",
    "items": "Order items",
    "itemCount": "items",
    "noItems": "No products were added to this order.",
    "unitPrice": "Unit Price:",
    "payment": "Pay for order",
    "paymentLoading": "Processing payment...",
    "paymentFailed": "Payment failed.",
    "cancelLoading": "Cancelling order...",
    "cancelConfirmDetail": "この注文をキャンセルしてもよろしいですか？",
    "cancelAuthRequired": "You must be logged in to cancel this order.",
    "cancelFailed": "The order could not be cancelled."
  },
  "orderDetail": {
    "loading": "Loading order details...",
    "title": "Order Details",
    "loginMessage": "Please log in to view this order.",
    "login": "Log in",
    "backToOrders": "Back to Orders",
    "continueShopping": "Continue Shopping",
    "paymentLoginRequired": "Please log in before making a payment.",
    "cancelConfirm": "この注文をキャンセルしてもよろしいですか？",
    "registered": "Order Registered",
    "orderNumber": "Order #{id}",
    "tracking": "Order Tracking",
    "statusDescription": "Order status is shown based on the latest recorded stage.",
    "cancelled": "Order has been cancelled",
    "notShipped": "This order has not entered the shipping process.",
    "currentStatus": "Current status:",
    "shippingInfo": "Shipping Information",
    "phone": "Phone Number",
    "address": "Shipping Address",
    "products": "Order Products",
    "productCount": "{count} items",
    "emptyProducts": "No products were registered for this order.",
    "quantity": "Quantity:",
    "unitPrice": "Unit Price:",
    "currency": "Toman",
    "totalAmount": "Total Amount",
    "viewAllOrders": "View All Orders"
  },
  "adminOwner": {
    "accessDenied": "オーナーのアクセスが必要です。",
    "accessModelDescription": "権限はストアごとに分離されます。",
    "activeAccess": "アクセスモデル",
    "addTeamMember": "チームメンバーを追加",
    "addTeamMemberDescription": "ストアメンバーを作成し、初期ロールを設定します。",
    "addingMember": "追加中...",
    "disabled": "無効",
    "enabled": "有効",
    "loadError": "オーナーコントロールセンターの読み込みに失敗しました。",
    "loadMembersError": "ストアメンバーの読み込みに失敗しました。",
    "memberAdded": "メンバーを追加しました。",
    "memberAddError": "メンバーの追加に失敗しました。",
    "memberRemoved": "メンバーを削除しました。",
    "memberRemoveError": "メンバーの削除に失敗しました。",
    "ownerOnly": "オーナーのアクセスが必要です。",
    "ownerStatus": "オーナーステータス",
    "ownerStatusDescription": "このストアのチームアクセスを管理します。",
    "people": "人",
    "permissionGranted": "このメンバーはこのモジュールにアクセスできます。",
    "permissionRestricted": "現在アクセスが制限されています。",
    "permissionProducts": "商品",
    "permissionCategories": "カテゴリー",
    "permissionInventory": "在庫",
    "permissionOrders": "注文",
    "permissionMembers": "メンバー",
    "permissionAppearance": "外観",
    "permissionStoreSettings": "ストア設定",
    "apiMapTitle": "API アクセスマップ",
    "apiMapDescription": "ストア管理モジュールごとに利用できる操作の概要です。",
    "apiMapStoreSettingsDescription": "ストアの構成と運用設定を表示および更新します。",
    "roleEditor": "編集者",
    "roleViewer": "閲覧者",
    "removeMember": "メンバーを削除",
    "permissionsLoadError": "メンバー権限の読み込みに失敗しました。",
    "permissionsSaved": "権限を保存しました。",
    "permissionsSaveError": "権限の保存に失敗しました。",
    "roleSaved": "ロールを更新しました。",
    "roleSaveError": "メンバーのロール更新に失敗しました。",
    "savePermissions": "権限を保存",
    "savingPermissions": "保存中...",
    "selectMember": "権限を管理するチームメンバーを選択してください。",
    "subtitle": "安全な一元のコントロールセンターで、ストアのチーム、ロール、アクセス権限を管理します。",
    "switchStore": "ストアを切り替え",
    "team": "ストアチーム",
    "title": "オーナーコントロールセンター"
  }
};
export default ja;
