# Generated by Django 5.2.17 on 2026-09-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_platformowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformowner',
            name='store_creation_limit',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of stores this platform owner can create.'),
        ),
    ]
