# Generated by Django 5.2.17 on 2026-09-10 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean')], default='text', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['product', 'key'], name='catalog_pro_product_a0f61b_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'key'), name='unique_product_attribute_key')],
            },
        ),
    ]
