# Generated by Django 5.2.17 on 2026-09-11 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Store Admin'), ('editor', 'Store Editor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner', 'is_active'], name='stores_stor_owner_i_c27bad_idx'),
        ),
        migrations.AddIndex(
            model_name='storemembership',
            index=models.Index(fields=['store', 'role'], name='stores_stor_store_i_845485_idx'),
        ),
        migrations.AddIndex(
            model_name='storemembership',
            index=models.Index(fields=['user', 'role'], name='stores_stor_user_id_b9dcf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='storemembership',
            constraint=models.UniqueConstraint(fields=('store', 'user'), name='unique_store_membership'),
        ),
    ]
