# Generated by Django 5.2.17 on 2026-09-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='default_locale',
            field=models.CharField(default='fa', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='enabled_locales',
            field=models.JSONField(default=list),
        ),
    ]
