# Generated by Django 5.2.17 on 2026-09-21 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMembershipPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='stores.storemembership')),
            ],
            options={
                'indexes': [models.Index(fields=['membership', 'code'], name='stores_stor_members_964627_idx'), models.Index(fields=['code'], name='stores_stor_code_589c6f_idx')],
                'constraints': [models.UniqueConstraint(fields=('membership', 'code'), name='unique_membership_permission')],
            },
        ),
    ]
